Fix conflict declarations of fork, pause, setup and sync
-----------------------------------------------------------------
[bochs@f24 linux-0.01]$ make
gcc -Wall -O -fstrength-reduce -fomit-frame-pointer -Werror -fno-builtin \
-nostdinc -Iinclude -c -o init/main.o init/main.c
In file included from init/main.c:2:0:
init/main.c:17:29: error: static declaration of ‘fork’ follows non-static declaration
 static inline _syscall0(int,fork)
                             ^
include/unistd.h:129:6: note: in definition of macro ‘_syscall0’
 type name(void) \
      ^~~~
include/unistd.h:204:5: note: previous declaration of ‘fork’ was here
 int fork(void);
     ^~~~
init/main.c:18:29: error: static declaration of ‘pause’ follows non-static declaration
 static inline _syscall0(int,pause)
                             ^
include/unistd.h:129:6: note: in definition of macro ‘_syscall0’
 type name(void) \
      ^~~~
include/unistd.h:218:5: note: previous declaration of ‘pause’ was here
 int pause(void);
     ^~~~~
init/main.c:20:29: error: static declaration of ‘sync’ follows non-static declaration
 static inline _syscall0(int,sync)
                             ^
include/unistd.h:129:6: note: in definition of macro ‘_syscall0’
 type name(void) \
      ^~~~
include/unistd.h:229:5: note: previous declaration of ‘sync’ was here
 int sync(void);
     ^~~~
init/main.c:79:6: error: return type of ‘main’ is not ‘int’ [-Werror=main]
------------------------------------------------------------------

Signed-off-by: Honggang Li <honggangli@163.com>